### ISSUE TITLE
layout-horizontal 

### ISSUE THREAD

**Issue by ProjectLinde37** [zuramai/mazer#48]
Is it possible to keep only the toolbar (main-navbar) on top when scrolling down?
The "header-top" is not essential on scrolling

**Comment by zuramai** [comment]
You can add `position: sticky` to `.main-navbar`

Add these styling in css:
```css
header {
  display: unset
}
.main-navbar {
  position: sticky;
  top: 0;
  z-index: 1
}
```
